### ISSUE TITLE
mycat-web新增mycat时一直处于loading状态，日志也没有输出错误

### ISSUE THREAD

**Issue by talkw-liu** [MyCATApache/Mycat-download#20]
![image](https://user-images.githubusercontent.com/11623379/51734164-aa077000-20be-11e9-98fc-dfb03fdeb2e4.png)
日志输出：
![image](https://user-images.githubusercontent.com/11623379/51734204-ca372f00-20be-11e9-8ceb-d05ba0297ab5.png)
添加mysql没有问题，添加mycat就有问题，mycat启动没有问题，mycat-web启动也没有错误日志

**Comment by yexianwolail** [comment]
我也是遇到同样的问题啊

**Comment by yexianwolail** [comment]
DEBUG: setDebug: JavaMail version 1.4ea
ERROR StatusLogger Could not set SMTPAppender message options. javax.mail.internet.AddressException: Illegal character in local name in string ``${sys:mail_from}''
        at javax.mail.internet.InternetAddress.checkAddress(InternetAddress.java:929)
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:819)
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:555)
        at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:91)
        at org.apache.logging.log4j.core.net.MimeMessageBuilder.parseAddress(MimeMessageBuilder.java:84)
        at org.apache.logging.log4j.core.net.MimeMessageBuilder.setFrom(MimeMessageBuilder.java:39)
        at org.apache.logging.log4j.core.net.SMTPManager$SMTPManagerFactory.createManager(SMTPManager.java:330)
        at org.apache.logging.log4j.core.net.SMTPManager$SMTPManagerFactory.createManager(SMTPManager.java:299)
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:71)
        at org.apache.logging.log4j.core.net.SMTPManager.getSMTPManager(SMTPManager.java:124)
        at org.apache.logging.log4j.core.appender.SMTPAppender.createAppender(SMTPAppender.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.logging.log4j.core.config.BaseConfiguration.createPluginObject(BaseConfiguration.java:913)
        at org.apache.logging.log4j.core.config.BaseConfiguration.createConfiguration(BaseConfiguration.java:667)
        at org.apache.logging.log4j.core.config.BaseConfiguration.createConfiguration(BaseConfiguration.java:659)
        at org.apache.logging.log4j.core.config.BaseConfiguration.doConfigure(BaseConfiguration.java:328)
        at org.apache.logging.log4j.core.config.BaseConfiguration.start(BaseConfiguration.java:166)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:341)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:386)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:149)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:84)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:35)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:257)
        at org.slf4j.helpers.Log4jLoggerFactory$PrivateManager.getContext(Log4jLoggerFactory.java:104)
        at org.slf4j.helpers.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:90)
        at org.slf4j.helpers.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:46)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
        at org.mycat.web.listen.PublishServiceStartupListener.<init>(PublishServiceStartupListener.java:14)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.mortbay.jetty.webapp.WebXmlConfiguration.newListenerInstance(WebXmlConfiguration.java:649)
        at org.mortbay.jetty.webapp.WebXmlConfiguration.initListener(WebXmlConfiguration.java:630)
        at org.mortbay.jetty.webapp.WebXmlConfiguration.initWebXmlElement(WebXmlConfiguration.java:367)
        at org.mortbay.jetty.webapp.WebXmlConfiguration.initialize(WebXmlConfiguration.java:289)
        at org.mortbay.jetty.webapp.WebXmlConfiguration.configure(WebXmlConfiguration.java:222)
        at org.mortbay.jetty.webapp.WebXmlConfiguration.configureWebApp(WebXmlConfiguration.java:180)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1231)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:460)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
        at org.mortbay.jetty.Server.doStart(Server.java:222)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.xml.XmlConfiguration.main(XmlConfiguration.java:985)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mortbay.start.Main.invokeMain(Main.java:194)
        at org.mortbay.start.Main.start(Main.java:523)
        at org.mortbay.start.Main.main(Main.java:119)

**Comment by yexianwolail** [comment]
DispatcherAction call:[mycatService.queryByPage] to spend:10ms
2019-03-13 15:00:23.402 INFO org.mycat.web.task.common.TaskManger:46 - 定时任务中的dbName列表:[]
2019-03-13 15:01:12.583 INFO org.mycat.web.util.DataSourceUtils:71 - dbname:mycat1MYCAT_MANGER is  initializing!!
2019-03-13 15:01:23.402 INFO org.mycat.web.task.common.TaskManger:46 - 定时任务中的dbName列表:[]
2019-03-13 15:01:23.403 INFO org.mycat.web.task.common.TaskManger:46 - 定时任务中的dbName列表:[]
2019-03-13 15:01:23.403 INFO org.mycat.web.task.common.TaskManger:46 - 定时任务中的dbName列表:[]
2019-03-13 15:02:23.402 INFO org.mycat.web.task.common.TaskManger:46 - 定时任务中的dbName列表:[]
2019-03-13 15:02:23.406 INFO org.mycat.web.task.common.TaskManger:46 - 定时任务中的dbName列表:[]
2019-03-13 15:02:23.407 INFO org.mycat.web.task.common.TaskManger:46 - 定时任务中的dbName列表:[]
