### ISSUE TITLE
这什么错误

### ISSUE THREAD

**Issue by a6965921** [MyCATApache/Mycat-download#30]
STATUS | wrapper  | 2021/12/30 12:36:47 | Starting the Mycat-server service...
STATUS | wrapper  | 2021/12/30 12:36:48 | --> Wrapper Started as Service
STATUS | wrapper  | 2021/12/30 12:36:48 | Launching a JVM...
INFO   | jvm 1    | 2021/12/30 12:36:49 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2021/12/30 12:36:49 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2021/12/30 12:36:49 | 
INFO   | jvm 1    | 2021/12/30 12:36:50 | 
INFO   | jvm 1    | 2021/12/30 12:36:50 | WrapperSimpleApp: Encountered an error running main: java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2021/12/30 12:36:50 | java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.MycatStartup.main(MycatStartup.java:53)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | Caused by: io.mycat.config.util.ConfigException: org.xml.sax.SAXParseException; lineNumber: 98; columnNumber: 45; 必须为元素类型 "user" 声明属性 "defaultAccount"。
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.config.loader.xml.XMLServerLoader.load(XMLServerLoader.java:111)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.config.loader.xml.XMLServerLoader.<init>(XMLServerLoader.java:69)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.config.loader.xml.XMLConfigLoader.<init>(XMLConfigLoader.java:56)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.config.ConfigInitializer.<init>(ConfigInitializer.java:77)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.config.MycatConfig.<init>(MycatConfig.java:72)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.MycatServer.<init>(MycatServer.java:144)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.MycatServer.<clinit>(MycatServer.java:96)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	... 7 more
INFO   | jvm 1    | 2021/12/30 12:36:50 | Caused by: org.xml.sax.SAXParseException; lineNumber: 98; columnNumber: 45; 必须为元素类型 "user" 声明属性 "defaultAccount"。
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.config.util.ConfigUtil.getDocument(ConfigUtil.java:115)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	at io.mycat.config.loader.xml.XMLServerLoader.load(XMLServerLoader.java:95)
INFO   | jvm 1    | 2021/12/30 12:36:50 | 	... 13 more
INFO   | jvm 1    | 2021/12/30 12:36:52 | Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=64M; support was removed in 8.0
STATUS | wrapper  | 2021/12/30 12:36:52 | <-- Wrapper Stopped
INFO   | wrapper  | 2021/12/30 12:36:53 | Waiting to start...
ERROR  | wrapper  | 2021/12/30 12:36:54 | The Mycat-server service was launched, but failed to start.

**Comment by zhangjian-txj** [comment]
这应该配置问题，server.xml或schema.xml的配置问题，

**Comment by zhangjian-txj** [comment]
mycat，用了几年了，没感觉又多好，也没感觉有多不好，偏重量，下个项目不考虑用了，还不如自己写一个基于mybatis写个读写分离的orm框架，自己用的还得劲。
