### ISSUE TITLE
reload @@config_all导致mycat不能连接

### ISSUE THREAD

**Issue by Zakispace** [MyCATApache/Mycat-download#8]
在正在使用的mycat的schema.xml添加了数据源，进行reload @@config_all，一直被卡住，最终导致之前的连接全部断开
错误日志：
07/05 17:52:44.755   WARN [$_NIOREACTOR-0-RW] (PhysicalDBPool.java:305) -localhost1 index:0 init connection error.
java.lang.NullPointerException
>-at org.opencloudb.backend.PhysicalDBPool.initSource(PhysicalDBPool.java:303)
>-at org.opencloudb.backend.PhysicalDBPool.init(PhysicalDBPool.java:254)
>-at org.opencloudb.backend.PhysicalDBNode.checkRequest(PhysicalDBNode.java:86)
>-at org.opencloudb.backend.PhysicalDBNode.getConnection(PhysicalDBNode.java:92)
>-at org.opencloudb.mysql.nio.handler.SingleNodeHandler.execute(SingleNodeHandler.java:159)
>-at org.opencloudb.server.NonBlockingSession.execute(NonBlockingSession.java:128)
>-at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:239)
>-at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
>-at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:102)
>-at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:77)
>-at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
>-at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
>-at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
>-at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
>-at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
>-at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
>-at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
>-at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
>-at java.lang.Thread.run(Thread.java:745)

**Comment by Zakispace** [comment]
MyCAT版本Server version: 5.5.8-mycat-1.5.1-RELEASE-20160504174159 MyCat Server (OpenCloundDB)
